version: '3.8'
services:
  postgresql:
    image: bitnami/postgresql:latest
    container_name: postgresql
    restart: always
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin
      - POSTGRESQL_DATABASE=bookstore
    ports:
      - 5432:5432
    volumes:
      - postgresql-data:/bitnami/postgresql
    networks:
      - bookstore

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092
    volumes:
      - kafka-data:/bitnami
    networks:
      - bookstore

  backend:
    container_name: backend
    build:
      dockerfile: service/Dockerfile
      context: .
      target: dev
    volumes:
      - ./service:/app
    depends_on:
      - postgresql
      - kafka
    restart: always
    ports:
      - 3000:3000
      - 9229:9229
    env_file:
      - ./service/.env
    networks:
      - bookstore

  frontend:
    container_name: frontend
    build:
      dockerfile: frontend/Dockerfile
      context: .
      target: dev
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: always
    ports:
      - 4000:3000
      - 9230:9229
    env_file:
      - ./frontend/.env
    networks:
      - bookstore

volumes:
  postgresql-data:
    driver: local
  kafka-data:
    driver: local

networks:
  bookstore:
    name: bookstore
